### ISSUE TITLE
Installation fail - pip: command not found

### ISSUE THREAD

**Issue by vincentux** [YunoHost-Apps/calibre_ynh#10]
J'ai rencontré ce souci à l'installation
`Warning: ./install: line 95: pip: command not found`

voici la ligne a corriger :  
https://github.com/YunoHost-Apps/calibre_ynh/blob/01e07ce2660f27b157a6cafeb8effc724e63fda7/scripts/install#L95

**Comment by Krakinou** [comment]
Étrange, pip est censé être installé avec python…
Sur quelle version de yunohost es-tu?
Que donne la commande `python -V`?

**Comment by vincentux** [comment]
> Sur quelle version de yunohost es-tu?
```
yunohost: 
  repo: stable
  version: 3.3.3
yunohost-admin: 
  repo: stable
  version: 3.3.1
moulinette: 
  repo: stable
  version: 3.3.1
ssowat: 
  repo: stable
  version: 3.3.2
```
>Que donne la commande python -V?  

`Python 2.7.13`
